/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "AppApi": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "Bucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "DeadLetterQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "MeiliSearchApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Table": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "UploadsQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}